[package]
name = "jarvis-spot-price-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
ctor = "0.1.22"
env_logger = "0.9.0"
gcp-bigquery-client = "0.9"
log = "0.4.14"
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
signal-hook = "0.3.13"
tokio = { version = "1", features = ["macros"] }
uuid = { version = "0.8", features = ["v4"] }
