apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarvis-spot-price-exporter.fullname" . }}
  labels:
    {{- include "jarvis-spot-price-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  keyfile.json: {{ .Values.secret.gcpServiceAccountKeyfile | toString | b64enc }}